In [1]:

import pandas as pd

df_data_1 = pd.read_csv('/project_data/data_asset/Shift.csv')
df_data_1.head()

,id,department,day,start time,end time,min req,max req,requested skills,duration,day index,start hour in week,end hour in week,Week start,Start date,End date
0,Emergency-Monday-2-8,Emergency,Monday,2,8,2,5,"Anaesthesiology,Cardiac",6,1,26,31,10/25/20 0:00,10/26/20 2:00,10/26/20 7:00
1,Emergency-Monday-8-12,Emergency,Monday,8,12,3,7,"Anaesthesiology,Cardiac",4,1,32,35,10/25/20 0:00,10/26/20 8:00,10/26/20 11:00
2,Emergency-Monday-12-18,Emergency,Monday,12,18,1,5,"Anaesthesiology,Cardiac",6,1,36,41,10/25/20 0:00,10/26/20 12:00,10/26/20 17:00
3,Emergency-Monday-18-2,Emergency,Monday,18,2,2,7,"Anaesthesiology,Cardiac",8,1,42,25,10/25/20 0:00,10/26/20 18:00,10/26/20 1:00
4,Consultation-Monday-8-12,Consultation,Monday,8,12,6,13,"Child Health, Aged Care",4,1,32,35,10/25/20 0:00,10/26/20 8:00,10/26/20 11:00